/*
 * SPDX-License-Identifier: EUPL-1.2
 * Copyright Regione Piemonte - 2022
 */

export const TICKET_STATUS_MAP = {
  TOTALLY_PAID: '001',
  PARTIALLY_PAID: '010',
  NOT_PAID: '015',
  CANCELLED: '800',
  REFUNDED: '801',
  CREDIT: '802'
};

export const REFOUND_METHOD_MAP = {
  VOUCHER: 1,
  BONIFICO: 2,
  BORSELLINO: 3
};

export const REFOUND_METHOD_MAP_LABELS = {
  [REFOUND_METHOD_MAP.VOUCHER]: "Voucher",
  [REFOUND_METHOD_MAP.BONIFICO]: "Bonifico",
  [REFOUND_METHOD_MAP.BORSELLINO]: "Borsellino",
};

export const TICKET_TYPES_MAP = {
  SSN: "TICKET SERVIZIO SANITARIO NAZIONALE",
  LIBERA_PROFESSIONE: "TICKET PER LIBERA PROFESSIONE",
  ALTRE_FATTURA: "A",
  ALTRE_RICEVUTA: "RICEVUTA"
};

export const TICKET_TYPES_MAP_CODES = {
  [TICKET_TYPES_MAP.SSN]: "S",
  [TICKET_TYPES_MAP.LIBERA_PROFESSIONE]: "L",
  [TICKET_TYPES_MAP.ALTRE_FATTURA]: "A",
  [TICKET_TYPES_MAP.ALTRE_RICEVUTA]: "R"
};

export const TICKET_TYPES_MAP_LABELS = {
  [TICKET_TYPES_MAP.SSN]: "TICKET SERVIZIO SANITARIO NAZIONALE",
  [TICKET_TYPES_MAP.LIBERA_PROFESSIONE]: "Libera Professione",
  [TICKET_TYPES_MAP.ALTRE_FATTURA]: "Altre posizioni debitorie - fattura",
  [TICKET_TYPES_MAP.ALTRE_RICEVUTA]: "Altre posizioni debitorie - ricevuta"
};

export const DELEGATION_STATUS_MAP = {
  ACTIVE: "ATTIVA",
  NOT_ACTIVE: "NON ATTIVA",
  REVOKED: "REVOCATA",
  REFUSED: "RIFIUTATA",
  IS_EXPIRING: "IN_SCADENZA",
  EXPIRED: "SCADUTA",
  UPDATED: "AGGIORNATA"
};
